require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const publicRoutes = require('./routes/public');
const adminRoutes = require('./routes/admin');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.use('/api', publicRoutes);
app.use('/admin', adminRoutes);
const PORT = process.env.PORT || 4000;
app.listen(PORT, ()=> console.log(`API running on http://localhost:${PORT}`));
